name: Dockerfile Lint

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile